### ISSUE TITLE
Color scheme default (light mode) => slate (dark mode)?

### ISSUE THREAD

**Issue by kiraum** [lpic2book/src#113]
Hi,
Probably just a personal preference on my side, but did you tried the slate (dark mode) color scheme? 
https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-scheme
https://github.com/lpic2book/src/blob/main/mkdocs.yml#L62

Dark mode seems to be more comfortable for reading.

Thanks!

**Comment by CoMPaTech** [comment]
Didn't try it but that makes proper sense - just searching for it: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=light+dark#automatic-light-dark-mode but unfortunately not available for non-sponsors (and as sponsors should not distribute source I don't think this non-profit repo/org would benefit as such with our CI). Switching and/or dual-publishing could be an option? Should I also add you to the repo so you can more conveniently commit?

**Comment by kiraum** [comment]
Thanks for the answer, but it's not needed to change because of me, I was just curious about the preferences, and if you tried it on mkdocs.

On my case I found an alternative, I'm using "dark mode" extension for Chrome ( https://mybrowseraddon.com/dark-mode.html ), not great if you are jumping between sites, but it does the job when reading the docs here, for example.

**Comment by CoMPaTech** [comment]
I didn't try it (yet) on mkdocs, but we can also generate two versions as a workaround :)
