### ISSUE TITLE
Odd "build" in "assemble section" of mdadm

### ISSUE THREAD

**Issue by stappersg** [lpic2book/src#12]
```text
to launch a pre existing array., *Build* Does not create array
```
is https://github.com/lpic2book/src/blob/main/docs/lpic2.204.1.md?plain=1#L232

That line with context
```text
#### Assemble

"Rebuilds" a pre existing array. Typically used when
migrating arrays to new hosts, but more often used from system startup
to launch a pre existing array., *Build* Does not create array
superblocks, and therefore does not destroy any pre existing data. May
be useful when attempting to recover or access stale data. (can not be
used in combination with `mdadm.conf `). Typically used with legacy
arrays, and rarely used.,
```

The `*Build*` feels very odd.
I think it should be start of a new section ...

**Comment by CoMPaTech** [comment]
Hi Geert, thanks for your contribution. Does #13 resolve this and look better to you?

**Comment by stappersg** [comment]
Only the first change.  The other two changes are completely unrelated.

Please avoid  yes/no questions.
Pretty please avoid  _yes/no question number one AND yes/no question number two_ constructions among programmers.

For a next time:
> What do you think about the change proposed in `#some_number`?


Even better:
> Yeah, _Build_ in a new section matches manual page of `mdadm`. It is now fixed. Thanks for reporting.

**Comment by CoMPaTech** [comment]
Hi Geert,

As indicated, please submit a PR - EnemyTurret or myself will happily review and merge it accordingly.

Thanks!

**Comment by stappersg** [comment]
That merge request became #14.
