### ISSUE TITLE
[Todo] Generate PDF in `pandoc/ubuntu-latex`, missing package.

### ISSUE THREAD

**Issue by mittler-works** [lpic2book/src#30]
I am currently trying to create a reproducible environment for converting this book to PDF using Docker. For this I use the script provided in `./bin/pdf.sh` however I get this error message indicating a missing package or something:

```
xdvipdfmx:fatal: Cannot proceed without .vf or "physical" font for PDF output...
```

I am using the official `pandoc/ubuntu-latex` image. For testing purposes, I installed `texlive-full` (including `texlive-fonts-*`) as well as `fonts-dejavu-*` and some other packages inside of the container. But still no luck. Could you point out the packages needed to build this book as pdf?

Epub works just fine.

**Comment by CoMPaTech** [comment]
I didn't spend any time on this when we (finally) converted it to markdown other than to make sure it was publishable as we now have on https://lpic2book.github.io/src/ - I included all that we had as scripts etc. for historical purposes but don't have the actual publishing pipeline setup requirements on hand, sorry.

https://www.linuxquestions.org/questions/showthread.php?p=6252065 contains some references to virtual fonts and how someone got it (partially) working - but we could also look at https://github.com/orzih/mkdocs-with-pdf or https://github.com/zhaoterryy/mkdocs-pdf-export-plugin within a container if that deems more useful?

**Comment by mittler-works** [comment]
Thank you for the information! Building the whole thing via mkdocs seems to make sense to me, since that is also used in the workflow to generate the HTML for github pages, if I saw that correctly. 
I'll take a closer look and come back with an MR when (if) I find a good solution.

In my opinion, it is nice to have the document also downloadable as PDF or epub. Perhaps such a solution could even be integrated into the workflow to automatically generate the assets for new releases as well.

By the way, thanks for publishing this book, it helps a lot in preparing for the LPIC exam! :rocket:

**Comment by CoMPaTech** [comment]
We used to have an epub/pdf published in both mobile platform stores but without proper maintenance that seemed less good of an idea, hence publishing it in the open for the community to improve and use. If (when) I have some spare time I can also take a look - let's leave this one open for someone to pick up, labelling accordingly.

**Comment by stappersg** [comment]
More text of the build failure:
```text
(/usr/share/texlive/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkeyval.tex
(/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkvutils.tex)))

LaTeX Font Warning: Font shape `TU/mdugm/m/n' undefined
(Font)              using `TU/lmr/m/n' instead on input line 186.

) (/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty
(/usr/share/texlive/texmf-dist/tex/latex/mathdesign/mdugm/t1mdugm.fd)))
(/tmp/tex2pdf.-5f4a40d326c3c96e/input.aux)
Runaway argument?
{\contentsline {subsection}{lsof}{12}{section*.21}\^^M
! File ended while scanning use of \@writefile.
<inserted text> 
                \par 
l.92 \begin{document}
                     
No pages of output.
Transcript written on /tmp/tex2pdf.-5f4a40d326c3c96e/input.log.

Error producing PDF.
! File ended while scanning use of \@writefile.
<inserted text> 
                \par 
l.92 \begin{document}
```

And yes, now I also outside my comfort zone.

**Comment by stappersg** [comment]
Mmm, there is no `cover.tex` in the git repository.

But when I modify `bin/pdf.sh` to not use it,
```diff
--- a/bin/pdf.sh
+++ b/bin/pdf.sh
@@ -2,10 +2,10 @@
 
 cd docs &&
 pandoc --pdf-engine=xelatex \
+  --verbose \
   -V lang="en-us" -V babel-lang=english \
   -V 'mainfont:DejaVuSerif.ttf' \
          -V 'sansfont:DejaVuSans.ttf' \
          -V 'monofont:DejaVuSansMono.ttf' \
          -V 'mathfont:texgyredejavu-math.otf' \
-         --include-before-body cover.tex \
          --toc -s *.md   -t pdf -o  ../dist/lpic2.pdf
```
the error presists ...

**Comment by stappersg** [comment]
FWIW #34 is also about creating a _.pdf_.

**Comment by CoMPaTech** [comment]
If someone's up for DTP-ing ... https://github.com/orzih/mkdocs-with-pdf has some options for styling the PDF
