### ISSUE TITLE
Backslash behaving unexpectedly when markdown is translated to html

### ISSUE THREAD

**Issue by EnemyTurret** [lpic2book/src#5]
In section 210.3 - LDAP Client Usage, the markdown reads:
```
Each entry can contain as many \<attrtype\>: \<attrvalue\> pairs as
needed.
```
but on the site it actually looks like this:
```
Each entry can contain as many \<attrtype>: \<attrvalue> pairs as needed.
```
**Note that the only first \\ is visible**, while the other behaves as expected.
This can be seen in the following paragraph too.
markdown:
```
Any value enclosed within a \"\<\" and a \"\>\" is a variable and
can be set whenever a new LDAP entry is created. This rule does not
apply, however, to \<id\>. The \<id\> is a number determined by the
application used to edit the entry.
```
site:
```
Any value enclosed within a \"\<\" and a \">\" is a variable and can be set whenever a new LDAP entry is created.
This rule does not apply, however, to \<id>. The \<id> is a number determined by the application used to edit the entry.
```

**Comment by stappersg** [comment]
@EnemyTurret meanwhile is #6 merged. For which reason should this issue remain open?

**Comment by EnemyTurret** [comment]
This issue describes a general unexpected behavior regarding backslashes, in some cases putting a backslash before a character in markdown escapes it and only the escaped character appears in the webpage, and in other cases the backslash appears as a literal character in the webpage.
#6 did not suffer from this issue because in that specific case the backslash behaved properly and escaped the `|` character.

**Comment by stappersg** [comment]
Currently / still at https://lpic2book.github.io/src/lpic2.210.3/

![afbeelding](https://user-images.githubusercontent.com/35434094/200311133-953d5a49-9e9d-4831-93e0-83b2e040f092.png)

**Comment by stappersg** [comment]
Since commit https://github.com/lpic2book/src/commit/c2dd58c0db7cb795c23b0e367c2e28e3b301d3c9

![afbeelding](https://user-images.githubusercontent.com/35434094/200311660-43170ea3-9df5-4dd4-a06a-7153b8acde00.png)

@EnemyTurret:  Please verify.

**Comment by EnemyTurret** [comment]
The site displays the correct content in this case because commit c2dd58c changed the markdown, however this issue describes a weird behavior in how the previous markdown was rendered.

**Comment by stappersg** [comment]
> > Please verify

>     ... correct content in this case ...

> however this issue describes a weird behavior in how the previous markdown was rendered.


I think it is **not** something for **this** project.

**Comment by stappersg** [comment]
> however this issue describes a weird behavior in how the previous markdown was rendered

**Not** something for **this** project.
